project:
  type: website
  output-dir: docs

website:
  title: "Biodiversity Genomics Europe & SciLifeLab Hi-C Course"
  favicon: img/favicon-32x32.png
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 35px
    search: true
    contents: 
     - index.qmd 
     - about.qmd
     - "<details><summary><a href='module1.qmd'>Introductory HiC Course</a></summary>
        </details>"
     - "<details><summary><a href='module2.qmd'>Challenging Samples Course</a></summary>
        </details>"
     - "<details><summary><a href='module3.qmd'>AssemblyLink HiC Course</a></summary>
        </details>"
     - protocols.qmd
     - instructors.qmd

  navbar:
      logo: "img/SciLifeLab_Logotype_NEG.png"
      background: "#A7C947"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



