project:
  type: website
  output-dir: docs

website:
  title: "BGE HiC Course"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
     - index.qmd 
     - about.qmd
     - presentations.qmd
     - protocols.qmd
     - module1.qmd
     - module2.qmd
     - module3.qmd
  navbar:
      logo: "img/SciLifeLab_Logotype_NEG.png"
      background: "#A7C947"
      left:
         - href: index.qmd
           text: Home
         - about.qmd
  favicon: "img/SciLifeLab_Logotype_NEG.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



