project:
  type: website
  output-dir: docs

website:
  title: "Biodiversity Genomics Europe HiC Course"
  favicon: img/favicon-32x32.png
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 35px
    search: true
    contents: 
     - index.qmd 
     - about.qmd
     - instructors.qmd
     - "<details><summary>Sessions</summary>
          <ul>
            <li><a href='module1.qmd'>Introductory HiC Technique</a></li>
            <li><a href='module2.qmd'>Challenging Sample Technique</a></li>
            <li><a href='module3.qmd'>AssemblyLink Technique</a></li>
            <li><a href='knowledgesharing.qmd'>Knowledge Sharing</a></li>
          </ul>
        </details>"
     - protocols.qmd

  navbar:
      logo: "img/SciLifeLab_Logotype_NEG.png"
      background: "#A7C947"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



