---
title: "Knowledge sharing"
---

The HiC course took place on June 9-14, 2024 at BMC Uppsala.

Please note that in order to view these files you must be granted access.

#### Knowledge sharing from the lab
At the end of the lab period, the AssemblyLink, Challenging Samples, and Introductory HiC groups gave an overview of their work, including discussion of the outcome.

[Giada Ferrari, presenting the Challenging Samples lab results](https://drive.google.com/file/d/1dHuQE5OKyNwxxJyllBlS-A9CbswXbNPK/view?usp=share_link)

[Irene Fabiola Roman Maldonado, presenting the Introductory HiC lab results](https://drive.google.com/file/d/1nwJvBZhVj7zqp5gHufoTaTQEL-4hiOlz/view?usp=share_link)

[Lily Shiue, presenting the AssemblyLink HiC lab results](https://drive.google.com/file/d/10Q4LVJL4i_7roPd0vKI6RoVxLuslCi1w/view?usp=share_link)

#### Knowledge sharing between institutions
##### Protocol differences
A representative from each institution presented the specifics of their sample handling

[Karine Labadie, Genoscope, presenting tissue grinding](https://drive.google.com/file/d/1bxRZR1gH19kbjjidTx2FqNuE12He_bvx/view?usp=share_link)

[Giada Ferrari, University of Oslo, presenting nuclei isolation used with plants](https://drive.google.com/file/d/1j1Kyrq_bXbUKnF3Br8rWYhXlJES3FCrj/view?usp=share_link)

##### Challenging Samples
Each institution presented their own handling of samples, including nuclei isolation, kits, what organisms they had success with, as well as sample outcomes.

[Fernando Cruz, CNAG, presenting a bioinformatic view of HiC QC](https://drive.google.com/file/d/1bDYEGac-cAr6W5AmN2XFxG3qLU5Rky-m/view?usp=share_link)

[Mårten Skage, University of Oslo, presenting results from Monogyna spp.](https://drive.google.com/file/d/1Czh992tfWnWOD9hmcqOHH-TOs1ZB4-Zp/view?usp=share_link)

[Mårten Skage, University of Oslo, presenting results from AssemblyLink on Fish Blood](https://drive.google.com/file/d/1vvJfDGH8jaVG7hZ7dKY29PLT1KdAbt7A/view?usp=share_link)

[Karine Labadie, Genoscope, presenting Plant and Lichen samples](https://drive.google.com/file/d/10izyMUFF4oMKHRPX44CSTNebyF1BjW7t/view?usp=share_link)

[Irene Fabiola Roman Maldonado, Sanger Institute, presenting plant and lichen protocols](https://drive.google.com/file/d/18V-3_Ex2u8Kpw5o8o2bnzRxyWDzDiaCM/view?usp=share_link)

[Lily Shiue, Dovetail, presenting AssemblyLink results with Meara and Algae](https://drive.google.com/file/d/1cn_TZnpGodunQdl-46eXS7oPY4WmoP_7/view?usp=share_link)

[Mårten Skage, University of Oslo, presents how to define and approach challenging samples](https://drive.google.com/file/d/1mHO5xM_V3VgEonK9Fl59M8Q1fbKGnS8n/view?usp=share_link)

[Brian Kilburn, Arima, presents on coral and sponge samples](https://drive.google.com/file/d/1FKwLXoIECHNFUf2rQIdC347Q97J6saJD/view?usp=share_link)


#### Presentations on Arima & Dovetail HiC protocols
The companies producing and validating the protocols and chemistries used in the course presented about their kits.

[Miles Collier, Dovetail, presents on AssemblyLink](https://drive.google.com/file/d/1EFBQyeFk5uq94SntI-anI1VTwSYPlKFR/view?usp=share_link)

[Brian Kilburn, Arima, presents on the Arima HiC protocol](https://drive.google.com/file/d/1E57ejkNEqRFWoGNO95GaSNoCk0egz_ki/view?usp=share_link)