---
title: "Introductory HiC Technique"
---

This group consisted of researchers with no previous experience of the HiC technique, and the course videos contain introductory content. The group was led by Mårten Skage (University of Oslo, NO) and Irene Fabiola Roman Maldonado (Sanger Institute, UK). Group participants were Fernando Cruz Rodriguez (CNAG, ES), Karine Labadie (Genoscope, FR), Graeme Oatley (Sanger Institute, UK), Simona Buonanno (UniBari, IT), Lorenzo Ballini (UniFi, IT), Leonardo Girlanda (UniFi, IT) and Annunziata Deluisi (UniBari, IT).

::: {.callout-caution}
## Note
- This content is currently in post-production and access is limited to participants
- If you require access, please contact the course administrators
:::

[Introduction and Safety Considerations](SAFETY VID)
Follow Irene and Mårten as they describe an overview of how the technique is scheduled, safety considerations, and some background on how the technique is implemented and developed in a production setting.

### Sample preparation
For the introductory group, herring and krill were used as sample types, and were prepared according to regular and low input protocols. Watch the following videos for a walkthrough of sample preparation.

Tissue weighing, handling tips and grinding with liquid nitrogen. Runtime: 22 minutes. 

[Sample preparation instruction](https://drive.google.com/file/d/1H5CMCjFoX3aD0uOgxNJAN_mu2_h3WSuz/view?usp=share_link)

Crosslinking the samples, and the importance of a homogenous solution. Runtime: 18 minutes.

[Sample crosslinking](https://drive.google.com/file/d/100MZf7saLs_6tznCrv679ohkbyI9IIqe/view?usp=share_link)

The krill samples are crosslinked first, and then tissue grinding with a power masher. Runtime: 6 minutes.

[Low input sample preparation](https://drive.google.com/file/d/1cpT7t-EEMbc6xZoPm4N_r4LqC6RlWuTG/view?usp=share_link)

### Estimating Input

Estimating input for krill and herring samples, and how low input and standard input approaches differ. Runtime: 10 minutes.

[Estimating input amount](https://drive.google.com/file/d/1a8ZyYmXpHVlH4Wukvulpofj51ZOYvdD9/view?usp=share_link) ** Note: for a demonstration of steps 5-11 including Qubit quantification, see the [Challenging Samples module](module2.qmd)!

### HiC Reactions

How to approach the decision on which input amounts to proceed with. Runtime: 10 minutes.

[Choosing samples for HiC reactions](https://drive.google.com/file/d/1t1gwGQv7STuMfQPp3ZHR2WmOGshgYM32/view?usp=share_link)

Follow along as the krill and herring are processed with the Arima HiC reactions. Runtime: 27 minutes.

[HiC Reactions](https://drive.google.com/file/d/1foQ3UE4qFe4GofpgEyRuKqJ0QdTYEOqS/view?usp=share_link)

### QC1

Considerations for when to proceed with QC1, and how the behaviour of the sample can indicate genomic differences. Runtime: 18 minutes.

[QC1](https://drive.google.com/file/d/1BBUcsHExm9d5D4pjgHHtHeNoY5gOO8Ka/view?usp=share_link)

Interpretation of QC1 results and an overview of the next steps. Runtime: 6 minutes.

[Discussion of results & next steps](https://drive.google.com/file/d/1PLTSypMIjMu0XVijPlk4Fc4Dcu9LduJ9/view?usp=share_link)