---
title: "Challenging Samples"
---

The group who worked with the challenging samples consisted of Giada Ferrari (University of Oslo), Pamela Veneziano Broccia (CNAG), Tuuli Lundbäck-Larva (SciLifeLab Uppsala), and Brian Kilburn (Arima).

::: {.callout-caution}
## Note
- The challenging samples content is currently in post-production and access is limited to participants
- If you require access, please contact the course administrators
:::

### Sample preparation

Eight challenging sample types were processed for Hi-C. Watch the following videos for a walkthrough of each sample up to the crosslinking step.

#### Lichens
Two lichen samples were processed by grinding in liquid nitrogen in a mortar and pestle. Runtime: 30 minutes.

[Lichen sample preparation](https://drive.google.com/file/d/10vvxCbuUXYkl43Tt9D483SS9isQ-9441/view?usp=share_link)

#### Flustra 
The Flustra sample was ground using liquid nitrogen as for the Lichen samples. Runtime: 2.5 minutes.

[Flustra sample preparation](https://drive.google.com/file/d/1v8DSWBrhU8NNgiDm-3rYNXDbO0l33MFR/view?usp=share_link)

#### Sponge
A sponge was processed using the "squeeze method"; a gentle extraction of nuclei from the sponge skeleton. Runtime: 30 minutes.

[Sponge sample preparation](https://drive.google.com/file/d/14DmAF65XEfB6XBdYzaPNCelA5CfpvNSZ/view?usp=share_link)

#### Algae (slime)
Processing of an algae that produces an extracellular matrix. Runtime: 5 minutes.

[Algae (slime) sample preparation](https://drive.google.com/file/d/1uL4Q_-f0gJJGnWvizKlr6YFjKHVIhUP9/view?usp=share_link)

#### Mosquitos
Sample processing of mosquitos. Two different sample preparations were performed. Runtime: 15 minutes.

[Mosquito sample preparation](https://drive.google.com/file/d/1gUEevdf9zuzoFJgb0fo7peU90ye_a_Ax/view?usp=share_link)

#### Worm
Discussion of sample processing - one individual crosslinked in its entirety and dissolved easily without further disruption. Runtime: 2 minutes.

[Worm sample preparation](https://drive.google.com/file/d/1Atfg-TFXjTQ7_1RLYotdSN6le6av_PLw/view?usp=share_link)

### Crosslinking
The eight sample types were batch processed from the crosslinking stage onwards. Includes discussion on handling insects, low input samples, recommended equipment, and sticky pellets. Runtime: 26 minutes.

[Crosslinking video](https://drive.google.com/file/d/12tlHYHO2MtPhJ7fxcl_TNwtDkYU56lGv/view?usp=share_link)

### Estimating Input
The estimating input protocol was performed on the two lichen samples. Runtime: 22 minutes.

[Estimating input video](https://drive.google.com/file/d/1b5StbVvYIWyMZv-D2udVmQZc0mZwKHqU/view?usp=share_link)

### HiC Reactions
Follow the challenging samples group as they perform the enzymatic reactions on the challenging samples. Kai from Arima joins for day 3 of the protocol! Runtime: 60 minutes.

[HiC Reactions video](https://drive.google.com/file/d/1HimIz-hKQ3SvkRFP1OtJChj2dyWf5NTG/view?usp=share_link)

### QC1
The last step for the challenging reactions is to follow the QC1 protocol. Runtime: 15 minutes.

[QC1 protocol and discussion for challenging samples](https://drive.google.com/file/d/1OCmwtyh_jOkeGDe2vNHUGu6il8EcjUQR/view?usp=share_link)